name: tester

on: 
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:

jobs:

  windows-2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2    

      - name: Testing
        shell: pwsh
        run: |
          dir
          dir c:\
          dir c:\qt
